# Git task: access to git configuration and system resources
filesystem:
  ro:
    - "{HOME}/.gitconfig"
    - "{XDG_CONFIG_HOME}/git/config"
    - "{XDG_CONFIG_HOME}/git/ignore"
    - "{XDG_CONFIG_HOME}/git/attributes"
    - "{HOME}/.ssh"
    - "{HOME}/.netrc"
    - "/etc/gitconfig"
    - "/etc/gitattributes"
    - "/etc/ssh/ssh_config"
    - "/etc/ssh/ssh_known_hosts"
  rw:
    - "{HOME}/.ssh/known_hosts"
    - "{HOME}/.git-credentials"
    - "{XDG_CONFIG_HOME}/git/credentials"
    - "{XDG_RUNTIME_DIR}/git/"
network:
  enabled: true
  connect_tcp:
    - "22"    # SSH (git@...)
    - "443"   # HTTPS (https://...)
    - "9418"  # Git protocol (git://...)
