# Jira CLI configuration
filesystem:
  ro:
    - "{HOME}/.jira.d"
  rw:
    - "{XDG_CONFIG_HOME}/.jira"
env:
    - JIRA_API_TOKEN
    - BITBUCKET_ACCESS_TOKEN
    - BITBUCKET_TOKEN
    - BITBUCKET_USERNAME
network:
  enabled: true
  connect_tcp:
    - "443"  # Jira API
